"""Build the static GitHub Pages demo from the bundled access-control example.

    python scripts/build_site.py --out _site

Copies the committed landing page, runs Enact on the passing and failing
example inputs, and publishes the generated HTML reports plus raw OSCAL JSON.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXAMPLE = ROOT / "examples" / "access-control"
STATIC = ROOT / "site"

EXPECTED = (
    "summary.html",
    "assessment-results.json",
    "poam.json",
)

NAV = """<nav class="demo-nav" aria-label="Demo">
  <a href="../../index.html">← Enact demo</a>
  <span>Generated by <code>enact run</code> from <code>examples/access-control/</code></span>
</nav>
<style>
  .demo-nav {
    display: flex; flex-wrap: wrap; justify-content: space-between; gap: .6rem;
    max-width: 1100px; margin: 0 auto; padding: .85rem 1.25rem;
    font: 15px/1.5 "Iowan Old Style", "Palatino Linotype", Palatino, serif;
    color: #57534e;
  }
  .demo-nav a { color: #1c1917; text-decoration: none; border-bottom: 1px solid #e7e0d6; }
  .demo-nav a:hover { border-color: #9a3412; color: #9a3412; }
  .demo-nav code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: .86em; }
</style>
"""


def _enact_cmd() -> list[str]:
    if shutil.which("uv"):
        return ["uv", "run", "enact"]
    if shutil.which("enact"):
        return ["enact"]
    return [sys.executable, "-m", "enact"]


def _run(cmd: list[str], *, expect_fail: bool = False) -> None:
    print("+", " ".join(cmd), flush=True)
    result = subprocess.run(cmd, cwd=ROOT)
    if expect_fail:
        if result.returncode != 1:
            raise SystemExit(f"expected enact to exit 1 for a failing run, got {result.returncode}")
        return
    if result.returncode != 0:
        raise SystemExit(result.returncode)


def _copy_static(out: Path) -> None:
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    for path in STATIC.iterdir():
        dest = out / path.name
        if path.is_dir():
            shutil.copytree(path, dest)
        else:
            shutil.copy2(path, dest)


def _inject_nav(html_path: Path) -> None:
    text = html_path.read_text(encoding="utf-8")
    if "<body>" not in text:
        raise SystemExit(f"{html_path} has no <body> tag")
    html_path.write_text(text.replace("<body>", "<body>\n" + NAV, 1), encoding="utf-8")


def _publish_run(src: Path, dest: Path) -> None:
    dest.mkdir(parents=True)
    missing = [name for name in EXPECTED if not (src / name).is_file()]
    if missing:
        raise SystemExit(f"{src} is missing generated files: {', '.join(missing)}")
    for name in EXPECTED:
        shutil.copy2(src / name, dest / name)
    _inject_nav(dest / "summary.html")
    for name in ("assessment-results.json", "poam.json"):
        json.loads((dest / name).read_text(encoding="utf-8"))


def build(out: Path) -> None:
    _copy_static(out)
    enact = _enact_cmd()
    work = ROOT / "out" / "site-build"
    if work.exists():
        shutil.rmtree(work)

    common = [
        "--oscal",
        str(EXAMPLE / "catalog.json"),
        "--manifest",
        str(EXAMPLE / "manifest.json"),
        "--workdir",
        str(EXAMPLE),
    ]
    _run(
        [
            *enact,
            "run",
            *common,
            "--input",
            str(EXAMPLE / "inputs" / "passing.json"),
            "--out",
            str(work / "pass"),
            "--title",
            "Access-control example (passing)",
        ]
    )
    _run(
        [
            *enact,
            "run",
            *common,
            "--input",
            str(EXAMPLE / "inputs" / "failing.json"),
            "--out",
            str(work / "fail"),
            "--title",
            "Access-control example (failing)",
        ],
        expect_fail=True,
    )
    _run(
        [
            *enact,
            "validate",
            "--assessment-results",
            str(work / "pass" / "assessment-results.json"),
            "--poam",
            str(work / "pass" / "poam.json"),
            "--catalog",
            str(EXAMPLE / "catalog.json"),
        ]
    )
    _run(
        [
            *enact,
            "validate",
            "--assessment-results",
            str(work / "fail" / "assessment-results.json"),
            "--poam",
            str(work / "fail" / "poam.json"),
        ]
    )

    examples = out / "examples"
    _publish_run(work / "pass", examples / "pass")
    _publish_run(work / "fail", examples / "fail")
    print(f"wrote {out}", flush=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--out",
        default=ROOT / "_site",
        type=Path,
        help="output directory (default: _site/)",
    )
    args = parser.parse_args(argv)
    build(args.out.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
